fix: change repayInput/withdrawlInput validation #107
DeFiGeek-Community/yamato-interface pull request #112
Opened 2021-11-12 06:17 UTC by deadrah

「返済量が借入量を超えています。」との修正指示でしたが、バリデート文言が長いとボタンが右にずれるのと、他を見ても「借入量を超えています。」のみで意味が通ると思われますのでこちらにしました。

2021-11-13 02:00 UTC, 0xTeaTwo requested changes
さっそくありがとうございます！
文言変更は承知しました。

数点コメントしたのでご確認お願いします。

また、Github Actionが走っていなかった問題を修正しました。お手数ですが、お手元のフォークリポジトリでupstreamを追随していただけないでしょうか:bow:UI上でやる場合は添付のスクショの赤丸で囲ったボタンを押してください。
![スクリーンショット 2021-11-13 10 45 23](https://user-images.githubusercontent.com/83848415/141601629-272c5d86-e15d-49ec-9843-90a3e1b915db.png)

2021-11-14 02:29 UTC, deadrah commented on src/components/Pledge/Debt/RepayInput.tsx
> +  const { cjpy } = useWalletState();
承知しました。修正しました。

2021-11-14 02:29 UTC, deadrah commented on src/constants/yamato.ts
> +  exceedsBalanceRepay: '返済量が残高を超えています。',
承知しました、明瞭ですね。修正しました。

2021-11-14 02:30 UTC, deadrah commented
再レビューお願いします！

2021-11-14 03:57 UTC, 0xTeaTwo approved these changes

2021-11-14 03:58 UTC, 0xTeaTwo commented
修正ありがとうございます。LGTMです。マージします！

2021-11-14 03:58 UTC, merged