feat(dashboard): Convert real time TX to ENS name if possible. #77
DeFiGeek-Community/yamato-interface pull request #129
Opened 2021-12-29 06:35 UTC by sibukixxx

EventLogで取得したaddressのENSを解決する #77
上記 Issue に関する Pull Request となります。

realtime TX のみを対象とし、 ethers.js の lookupAddress を利用しています。

2021-12-29 06:37 UTC, sibukixxx commented
@0xTeaTwo 
レビューお願いいたします

2022-01-06 04:14 UTC, 0xTeaTwo requested changes
ありがとうございます！大筋は良さそうです。

ご意見を伺ってみたいのですが、キャッシュを持つならどのような設計が考えられるでしょうか？というのも毎回このログの全てにENS解決を行うのは被りの名前も多そうでだいぶ無駄になりそうです。また、5秒毎ですし、ethers.js経由だとブロック番号指定しか出来ないため20件を超えて大量のログが発生します。

2022-01-06 04:14 UTC, 0xTeaTwo commented on src/utils/web3.ts
> +export async function shortenAddressOrEns(address: string, chars = 4): Promise<string> {
関数の名前は、一つ上と入れ違っていますか？

2022-01-06 04:15 UTC, 0xTeaTwo commented
circle CIが動いていないようなので、設定を調整します。

2022-01-07 08:46 UTC, sibukixxx commented
@0xTeaTwo 
キャッシュということは、何かしら外部のストレージ（Redisなど）があることが前提でしょうか？

2022-01-07 09:12 UTC, 0xTeaTwo commented
@sibukixxx 
あくまでフロントエンドですね。LocalStorageだとENSを変えたときに更新できなくなりそうなので、普通にjsのメモリ上の話で良いと思います。reduxベースのためstoreを利用してlookupAddressの結果を溜めていくのがファーストチョイスでしょうか。

2022-01-08 06:57 UTC, sibukixxx commented on src/utils/web3.ts
> +export async function shortenAddressOrEns(address: string, chars = 4): Promise<string> {
@0xTeaTwo 
入れ違って、、ますね。
再コミットいたします

2022-01-08 06:58 UTC, sibukixxx commented
@0xTeaTwo 
> reduxベースのためstoreを利用してlookupAddressの結果

フロントエンドで redux ベースであれば、store の利用に私も賛成です

2022-01-08 07:59 UTC, 0xTeaTwo commented on src/utils/web3.ts
> +export async function shortenAddressOrEns(address: string, chars = 4): Promise<string> {
@sibukixxx すいません、この修正だけコミット上げてもらってもよいでしょうか？キャッシュの話は別PRでも良いと考えていることと、Circel CIの設定を変えているのでそのテストを兼ねさせていただきたく...

2022-01-08 08:04 UTC, 0xTeaTwo commented on src/utils/web3.ts
> +export async function shortenAddressOrEns(address: string, chars = 4): Promise<string> {
基本的には動くはずですが、個人アカウントでCircleCIを開設していて、かつフォークしたリポジトリをフォローしているとCIの実行コンテキストがフォークリポジトリ側に持っていかれるという罠があるようです。

2022-01-16 08:55 UTC, sibukixxx commented on src/utils/web3.ts
> +export async function shortenAddressOrEns(address: string, chars = 4): Promise<string> {
@0xTwo 
テストについてご相談です。
固定値として変動しない ENS として利用できるものはあるでしょうか？
※ アドレスが指す name が頻繁に変わるとなると汎用的なテストができなかったためです

2022-01-19 08:59 UTC, 0xTwo commented on src/utils/web3.ts
> +export async function shortenAddressOrEns(address: string, chars = 4): Promise<string> {
@sibukixxx pushありがとうございます。うーん、やっぱりcircleCIが動いていないですね。上記コメントの状況になっていたりするでしょうか？（フォークリポジトリ側でCIが動いている状況ということです）

2022-01-19 09:04 UTC, 0xTwo commented on src/utils/web3.ts
> +export async function shortenAddressOrEns(address: string, chars = 4): Promise<string> {
> テストについてご相談です。
> 固定値として変動しない ENS として利用できるものはあるでしょうか？
> ※ アドレスが指す name が頻繁に変わるとなると汎用的なテストができなかったためです

これはcircleCIではなくユニットテストということでよろしいでしょうか？であれば、外部関数である`getEnsName`をjestでmockして任意の値を返すので良いと思います。

2022-01-19 09:10 UTC, 0xTwo commented on src/utils/web3.ts
> +export async function shortenAddressOrEns(address: string, chars = 4): Promise<string> {
> テストについてご相談です。
> 固定値として変動しない ENS として利用できるものはあるでしょうか？
> ※ アドレスが指す name が頻繁に変わるとなると汎用的なテストができなかったためです

これはcircleCIではなくユニットテストということでよろしいでしょうか？であれば、外部関数である`lookupAddress`をjestでmockして任意の値を返すので良いと思います。

2026-01-12 10:09 UTC, closed without merging