fix: issue#104
DeFiGeek-Community/yamato-interface pull request #138
Opened 2022-02-20 12:19 UTC by taka0409

fix: https://github.com/DeFiGeek-Community/yamato-interface/issues/104

- 初期値とメタマスクトランザクション発行後の初期値を空文字にする
- 空文字はバリデーションエラー対象としない
- 空文字のとき実行ボタンを非活性化

対応イメージ
![image](https://user-images.githubusercontent.com/32897506/154842099-6dab4643-bfb5-491e-aa2e-0eaac075eb3f.png)

2022-02-23 13:58 UTC, 0xTwo requested changes

2022-02-23 13:58 UTC, 0xTwo commented on src/components/Pledge/Collateral/DepositInput.tsx
> +        deposit: string;
これらの型定義も`number | string`ではないでしょうか？

2022-02-23 13:58 UTC, 0xTwo commented on src/components/Pledge/Collateral/DepositInput.tsx
> +      if (typeof values.deposit === 'number') {
早期リターンで記述した方が構造が把握しやすくなると思います。他のバリデートが必要になったときなども踏まえて。バリデートの順番を入れ替えられたときのガードはTSのコンパイラが頑張ってくれるでしょうw
```
if (typeof values.deposit !== 'number') {
   return;
}
```

2022-02-23 13:58 UTC, 0xTwo commented on src/components/Pledge/Debt/BorrowingInput.tsx
> +        borrowing: string;
これらの型定義も`number | string`ではないでしょうか？

2022-02-23 13:58 UTC, 0xTwo commented on src/components/Pledge/Collateral/DepositInput.tsx
> +            {typeof deposit === 'number' && deposit > 0 && (
👍

2022-02-23 15:18 UTC, taka0409 commented on src/components/Pledge/Collateral/DepositInput.tsx
> +      if (typeof values.deposit === 'number') {
そのように対応します。

2022-02-23 15:24 UTC, taka0409 commented on src/components/Pledge/Collateral/DepositInput.tsx
> +        deposit: string;
そうすると

> 型 '(values: { deposit: number | string; }, formikHelpers: FormikHelpers<{ deposit: number | string; }>) => Promise<void>' 
> を
> 型 '((values: { deposit: string; }, formikHelpers: FormikHelpers<{ deposit: string; }>) => void | Promise<any>) & ((values: { deposit: string | number; }, formikHelpers: FormikHelpers<...>) => Promise<...>)' 
> に割り当てることはできません。
というエラーが`<Formik initialValues={{ deposit: '' }} onSubmit={submitDeposit}>`で発生します。
initialvaluesがstringであり（number | stringでない）submitは同じ型を受け入れる必要がある（関数内でnumberとして処理できるのはTypeScriptのおかげ？）からかなとおもいますがこの解消方法わかりますでしょうか？
型推論で無理やりと言っているのもこの部分だったりします。

2022-02-24 01:17 UTC, 0xTwo commented on src/components/Pledge/Collateral/DepositInput.tsx
> +        deposit: string;
型推論を無効にするのは型アサーション`as`ですね！本件の推論元になっているであろうところを`initialValues={{ deposit: '' as number| string}}`とすればいけるのではないでしょうか。

2022-02-24 10:37 UTC, taka0409 commented on src/components/Pledge/Collateral/DepositInput.tsx
> +        deposit: string;
なるほど、ありがとうございます。それで動きました。

2022-02-26 02:43 UTC, 0xTwo approved these changes

2022-02-26 02:47 UTC, 0xTwo commented
ありがとうございます。ソースコメントにwhyを書いておいたほうがよいなとも思いましたが、コミットメッセージにイシューナンバー書いているのでLGTMです。マージします！

2022-02-26 02:47 UTC, merged